apiVersion: v1
appVersion: "apps/v1"
description: A Helm chart for Kubernetes
name: chart-cloud
version: 0.1.0
kubeVersion: ">=v1.14.10-gke.17"
#keywords:
#  - app
#  - python
home: https://github.com/fuchicorp/cloud
sources:
  - https://github.com/fuchicorp/cloud.git
maintainers:
  - name: FuchiCorp
    email: fuchicorpsolution@gmail.com
    url: https://github.com/fuchicorp
icon: https://avatars3.githubusercontent.com/u/46357473?s=200&v=4
tillerVersion: v2.11.0

